
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bwapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bwapp
  template:
    metadata:
      labels:
        app: bwapp
    spec:
      containers:
      - name: bwapp
        image: placeholder
        ports:
        - containerPort: 80
