
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bwapp
  namespace: bwappns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bwapp
  template:
    metadata:
      labels:
        app: bwapp
    spec:
      containers:
      - name: bwapp
        image: githubregistryjfa.azurecr.io/bwapp-app:latest
        ports:
        - containerPort: 80
